const fs = require('fs');
const path = require('path');
const { withInfoPlist, withEntitlementsPlist, withXcodeProject, withDangerousMod, IOSConfig } = require('@expo/config-plugins');

// Real PushKit + CallKit wiring for genuine phone-call-style ringing on
// iOS — a regular remote push (what this app used before) cannot wake the
// app to show the native full-screen incoming-call UI, ring through
// silent mode, or reliably fire when the app is force-quit. Only PushKit
// VoIP pushes handled via CallKit get that behavior; this is an Apple
// platform requirement, not something achievable from JS alone.
//
// react-native-voip-push-notification + react-native-callkeep both ship
// real native iOS modules (see their podspecs) but neither publishes an
// Expo config plugin that wires up PKPushRegistryDelegate — their setup
// docs assume a hand-edited AppDelegate, which this managed project
// doesn't keep checked in (EAS Build regenerates ios/ from scratch on
// every build via `expo prebuild`).
//
// First attempt (build 122, take 1) injected the delegate straight into
// the generated Swift AppDelegate and referenced the two pods'
// Objective-C classes by name from Swift — that fails to compile
// ("cannot find X in scope") because those pods aren't exposed to Swift
// without a bridging header, and wiring one up via SWIFT_OBJC_BRIDGING_HEADER
// build settings turned out unreliable against Expo's generated project.
//
// This version sidesteps Swift entirely: it adds a small, self-contained
// Objective-C source file to the Xcode project. Objective-C's `+load`
// runs automatically the moment the class is loaded into the process —
// before `main()` even runs — so the PushKit registry can be set up
// without touching AppDelegate.swift or crossing the Swift/ObjC bridge
// at all. The pod headers are imported directly (plain Objective-C to
// Objective-C), so there's no bridging-header step to get wrong.
//
// IMPORTANT: this has not been build-tested against a real device yet —
// Objective-C can't be compiled or verified in this sandbox, only on
// EAS's macOS build workers. Treat the first few EAS builds after this
// lands as integration testing, not a guaranteed first-try success.

const HANDLER_CLASS_NAME = 'PryvoVoipPushHandler';
const HEADER_FILE_NAME = `${HANDLER_CLASS_NAME}.h`;
const IMPL_FILE_NAME = `${HANDLER_CLASS_NAME}.m`;

const GENERATED_MARKER = '// @generated by plugins/withCallKeepVoip.js — do not edit by hand, it is overwritten on every prebuild.';

function withVoipBackgroundMode(config) {
  return withInfoPlist(config, (config) => {
    const modes = config.modResults.UIBackgroundModes ?? [];
    if (!modes.includes('voip')) modes.push('voip');
    config.modResults.UIBackgroundModes = modes;
    return config;
  });
}

// CallKit itself needs no special entitlement beyond the standard Push
// Notifications capability (already implied by expo-notifications being
// installed) — this is a no-op placeholder kept for symmetry/clarity and
// as the obvious place to add one if a future CallKit feature needs it.
function withCallKeepEntitlements(config) {
  return withEntitlementsPlist(config, (config) => config);
}

function headerContents() {
  return `${GENERATED_MARKER}
#import <Foundation/Foundation.h>

@interface ${HANDLER_CLASS_NAME} : NSObject
@end
`;
}

function implContents() {
  return `${GENERATED_MARKER}
#import "${HEADER_FILE_NAME}"
#import <PushKit/PushKit.h>
#import "RNVoipPushNotificationManager.h"
#import <RNCallKeep/RNCallKeep.h>

@interface ${HANDLER_CLASS_NAME} () <PKPushRegistryDelegate>
@property (nonatomic, strong) PKPushRegistry *voipRegistry;
@end

@implementation ${HANDLER_CLASS_NAME}

// Runs automatically when the Objective-C runtime loads this class into
// the process — earlier than applicationDidFinishLaunching, and without
// needing any hook in AppDelegate. Apple recommends registering for VoIP
// pushes as early as possible; this is about as early as it gets.
+ (void)load {
  static ${HANDLER_CLASS_NAME} *sharedHandler = nil;
  static dispatch_once_t onceToken;
  dispatch_once(&onceToken, ^{
    sharedHandler = [${HANDLER_CLASS_NAME} new];
    sharedHandler.voipRegistry = [[PKPushRegistry alloc] initWithQueue:dispatch_get_main_queue()];
    sharedHandler.voipRegistry.delegate = sharedHandler;
    sharedHandler.voipRegistry.desiredPushTypes = [NSSet setWithObject:PKPushTypeVoIP];
  });
}

- (void)pushRegistry:(PKPushRegistry *)registry didUpdatePushCredentials:(PKPushCredentials *)credentials forType:(PKPushType)type {
  [RNVoipPushNotificationManager didUpdatePushCredentials:credentials forType:(NSString *)type];
}

- (void)pushRegistry:(PKPushRegistry *)registry didInvalidatePushTokenForType:(PKPushType)type {
  // No action needed — see react-native-voip-push-notification docs.
}

- (void)pushRegistry:(PKPushRegistry *)registry didReceiveIncomingPushWithPayload:(PKPushPayload *)payload forType:(PKPushType)type withCompletionHandler:(void (^)(void))completion {
  NSString *uuid = payload.dictionaryPayload[@"uuid"] ?: [[NSUUID UUID] UUIDString];
  NSString *callerName = payload.dictionaryPayload[@"callerName"] ?: @"Unknown";
  NSString *handle = payload.dictionaryPayload[@"handle"] ?: callerName;
  BOOL hasVideo = [payload.dictionaryPayload[@"hasVideo"] boolValue];

  [RNVoipPushNotificationManager addCompletionHandler:uuid completionHandler:completion];
  [RNVoipPushNotificationManager didReceiveIncomingPushWithPayload:payload forType:(NSString *)type];

  // Apple requires CallKit to be invoked synchronously here on iOS 13+
  // or the OS may terminate the app / stop delivering future VoIP
  // pushes — see react-native-callkeep's README for the same warning.
  [RNCallKeep reportNewIncomingCall:uuid
                              handle:handle
                          handleType:@"generic"
                            hasVideo:hasVideo
                 localizedCallerName:callerName
                     supportsHolding:NO
                        supportsDTMF:NO
                    supportsGrouping:NO
                  supportsUngrouping:NO
                         fromPushKit:YES
                             payload:payload.dictionaryPayload
               withCompletionHandler:nil];

  completion();
}

@end
`;
}

function withVoipPushHandlerFiles(config) {
  return withDangerousMod(config, [
    'ios',
    async (config) => {
      const iosRoot = path.join(config.modRequest.platformProjectRoot, config.modRequest.projectName);
      fs.mkdirSync(iosRoot, { recursive: true });
      fs.writeFileSync(path.join(iosRoot, HEADER_FILE_NAME), headerContents());
      fs.writeFileSync(path.join(iosRoot, IMPL_FILE_NAME), implContents());
      return config;
    },
  ]);
}

function withVoipPushHandlerXcodeTarget(config) {
  return withXcodeProject(config, (config) => {
    const project = config.modResults;
    const projectName = config.modRequest.projectName;
    const relativeImplPath = `${projectName}/${IMPL_FILE_NAME}`;

    // Idempotent across repeated local `expo prebuild` runs (EAS Build
    // always starts from a clean ios/ so this branch is mostly a
    // local-dev safety net).
    if (project.hasFile(relativeImplPath)) {
      return config;
    }

    const { uuid: targetUuid } = IOSConfig.XcodeUtils.getApplicationNativeTarget({
      project,
      projectName,
    });

    IOSConfig.XcodeUtils.addBuildSourceFileToGroup({
      filepath: relativeImplPath,
      groupName: projectName,
      project,
      targetUuid,
    });

    return config;
  });
}

module.exports = function withCallKeepVoip(config) {
  config = withVoipBackgroundMode(config);
  config = withCallKeepEntitlements(config);
  config = withVoipPushHandlerFiles(config);
  config = withVoipPushHandlerXcodeTarget(config);
  return config;
};
